//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MasterSaleReturn
    {
        public int SaleReturnID { get; set; }
        public int TranID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Voucher { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<bool> IsDelivery { get; set; }
        public Nullable<decimal> VoucherDis { get; set; }
        public Nullable<decimal> AdvancedPayAmt { get; set; }
        public Nullable<decimal> FOCAmt { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> ChargesAmt { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
        public Nullable<int> CreditLimitDay { get; set; }
    }
}
